name: Test Flaky Pipeline Locally

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  run-flamma:
    uses: Beatriz-dos-Anjos/FlaMMA-Flaky-Mitigation-Monitoring-Approach/.github/workflows/detector.yml@chore/cd
    secrets: inherit
